# -*- coding: utf-8 -*-
"""PROYECTO-TESIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpKUHf2duB3iTmDQ34QWyCRIKtkxtRlt

##RECONSTRUCCION DE LA BASE DE DATOS
"""

from google.colab import drive
drive.mount('/content/drive')

# Use a pipeline as a high-level helper
!pip install sacremoses

from transformers import pipeline

pipe = pipeline("translation", model="Helsinki-NLP/opus-mt-en-es")

!python -m spacy download es_core_news_sm

def traducir_texto(texto, pipe):
    try:
        return pipe(texto)[0]['translation_text']
    except Exception as e:
        print(f"Error al traducir: {e}")
        return texto

def traducir_archivo(archivo_entrada, archivo_salida, modelo='Helsinki-NLP/opus-mt-en-es'):
    pipe = pipeline("translation_en_to_es", model=modelo)

    with open(archivo_entrada, 'r', encoding='latin-1') as f:
        lineas = f.readlines()

    traducciones = [traducir_texto(linea.strip(), pipe) for linea in lineas if linea.strip()]

    with open(archivo_salida, 'w', encoding='latin-1') as f:
        for traduccion in traducciones:
            f.write(traduccion + '\n')

    print(f"Texto traducido guardado en {archivo_salida}")

# Rutas de los archivos de entrada y salida
archivo_entrada = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/g13-planningpoker.txt'
archivo_salida = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/traducciones/g13-planningpoker-traducido.txt'
traducir_archivo(archivo_entrada, archivo_salida)

import os
import json
import spacy
from pathlib import Path

# Carpeta destino
carpeta_destino = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis'
os.makedirs(carpeta_destino, exist_ok=True)

# Cargar modelo
nlp = spacy.load("es_core_news_sm")

def algoritmo_1_tokenizacion_desde_archivo(ruta_archivo):
    """
    Entrada:
        ruta_archivo (str): archivo .txt con múltiples historias de usuario
    Salida:
        Lista de historias tokenizadas (una lista de tokens por historia)
    """
    ruta = Path(ruta_archivo)
    texto = ruta.read_text(encoding="latin-1")

    # Separar historias por líneas no vacías
    historias = [linea.strip() for linea in texto.split("\n") if linea.strip()]

    resultado = []
    for historia in historias:
        doc = nlp(historia)
        tokens = [token.text for token in doc if not token.is_space]
        resultado.append(tokens)

    return resultado

# INPUT (archivo .txt)
archivo_entrada = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/traducciones/g13-planningpoker-traducido.txt'

# 👉 AQUÍ estabas fallando: ejecutar el algoritmo
tokens_por_historia = algoritmo_1_tokenizacion_desde_archivo(archivo_entrada)

# OUTPUT (JSON)
archivo_json = os.path.join(
    carpeta_destino,
    'algoritmo1_tokenizacion_g13-planningpoker.json'
)

with open(archivo_json, 'w', encoding='latin-1') as f:
    json.dump(tokens_por_historia, f, ensure_ascii=False, indent=2)

print("Archivo guardado como:", archivo_json)

import os
import json
import spacy

nlp = spacy.load("es_core_news_sm")

archivo_tokens = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo1_tokenizacion_g13-planningpoker.json'

carpeta_destino = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis'
archivo_salida_pos = os.path.join(
    carpeta_destino,
    'algoritmo2_pos_g13-planningpoker.json'
)

with open(archivo_tokens, 'r', encoding='latin-1') as f:
    tokens_por_historia = json.load(f)

print("Historias cargadas:", len(tokens_por_historia))

def algoritmo_2_pos_tagging(tokens_por_historia):
    """
    Entrada:
        Lista de historias tokenizadas
    Salida:
        Lista de historias con (token, POS)
    """
    resultado = []

    for tokens in tokens_por_historia:
        texto = " ".join(tokens)
        doc = nlp(texto)

        historia_pos = []
        for token in doc:
            if not token.is_space:
                historia_pos.append((token.text, token.pos_))

        resultado.append(historia_pos)

    return resultado

pos_por_historia = algoritmo_2_pos_tagging(tokens_por_historia)
with open(archivo_salida_pos, 'w', encoding='latin-1') as f:
    json.dump(pos_por_historia, f, ensure_ascii=False, indent=2)

print("Archivo POS guardado en:", archivo_salida_pos)

import os
import json

# ===============================
# RUTAS DE ENTRADA / SALIDA
# ===============================

archivo_pos = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo2_pos_g13-planningpoker.json'

carpeta_destino = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis'
archivo_entidades = os.path.join(
    carpeta_destino,
    'algoritmo3_entidades_g13-planningpoker.json'
)

# ===============================
# CARGA DEL JSON POS
# ===============================

with open(archivo_pos, 'r', encoding='latin-1') as f:
    pos_por_historia = json.load(f)

print("Historias cargadas:", len(pos_por_historia))

# ===============================
# FUNCIONES AUXILIARES
# ===============================

# Conectores lingüísticos para BENEFICIO
CONECTORES_BENEFICIO = [
    ["para"],
    ["para", "que"],
    ["de", "modo", "que"],
    ["a", "fin", "de"],
    ["con", "el", "fin", "de"]
]

def extraer_beneficio(historia):
    tokens = [t[0].lower() for t in historia]
    posiciones = []

    for conector in CONECTORES_BENEFICIO:
        n = len(conector)
        for i in range(len(tokens) - n):
            if tokens[i:i+n] == conector:
                posiciones.append(i + n)

    if posiciones:
        inicio = max(posiciones)
        beneficio = [
            historia[j][0]
            for j in range(inicio, len(historia))
            if historia[j][1] != "PUNCT"
        ]
        return " ".join(beneficio)

    return None



def extraer_contexto(historia):
    """
    Extrae un contexto semántico básico a partir de sustantivos
    y modificadores cercanos
    """
    contexto = []
    for i, (token, pos) in enumerate(historia):
        if pos == "NOUN":
            frase = [token]

            for j in range(i + 1, min(i + 4, len(historia))):
                t, p = historia[j]
                if p in ["ADJ", "ADP", "NOUN"]:
                    frase.append(t)
                else:
                    break

            contexto.append(" ".join(frase))

    return list(set(contexto))

VERBOS_DEBILES = {
    "quiero", "querer",
    "poder", "puedo", "pueda",
    "gustaría", "desearía", "necesito"
}

def extraer_accion_semantica(historia):
    """
    Extrae el primer verbo semántico relevante,
    ignorando verbos débiles como 'quiero'
    """
    for token, pos in historia:
        if pos == "VERB" and token.lower() not in VERBOS_DEBILES:
            return token
    return None


# ===============================
# ALGORITMO 3
# ===============================

def algoritmo_3_reconocimiento_entidades_con_contexto(pos_por_historia):
    resultados = []

    for historia in pos_por_historia:
        entidades = {
            "ROL": [],
            "ACCIÓN": [],
            "OBJETO": [],
            "BENEFICIO": [],
            "CONTEXTO": []
        }

        tokens = [t[0].lower() for t in historia]

        # -------- ROL --------
        if "como" in tokens:
            idx = tokens.index("como")
            for i in range(idx + 1, len(historia)):
                token, pos = historia[i]
                if pos == "NOUN":
                    entidades["ROL"].append(token)
                    break

        # -------- ACCIÓN --------
        accion = extraer_accion_semantica(historia)
        if accion:
          entidades["ACCIÓN"].append(accion)


        # -------- OBJETO --------
        accion_encontrada = False
        for token, pos in historia:
            if pos == "VERB" and token.lower() not in VERBOS_DEBILES:
                accion_encontrada = True
                continue
            if accion_encontrada and pos == "NOUN":
                entidades["OBJETO"].append(token)
                break


        # -------- BENEFICIO --------
        beneficio = extraer_beneficio(historia)
        if beneficio:
            entidades["BENEFICIO"].append(beneficio)

        # -------- CONTEXTO --------
        entidades["CONTEXTO"] = extraer_contexto(historia)

        resultados.append(entidades)

    return resultados

# ===============================
# EJECUCIÓN Y GUARDADO
# ===============================

entidades_por_historia = algoritmo_3_reconocimiento_entidades_con_contexto(pos_por_historia)

with open(archivo_entidades, 'w', encoding='latin-1') as f:
    json.dump(entidades_por_historia, f, ensure_ascii=False, indent=2)

print("Archivo de entidades guardado en:")
print(archivo_entidades)

import os
import json

# ===============================
# RUTAS
# ===============================

archivo_entidades = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo3_entidades_g13-planningpoker.json'

carpeta_destino = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis'
archivo_relaciones = os.path.join(
    carpeta_destino,
    'algoritmo4_relaciones_g13-planningpoker.json'
)

# ===============================
# CARGA DE ENTIDADES
# ===============================

with open(archivo_entidades, 'r', encoding='latin-1') as f:
    entidades_por_historia = json.load(f)

print("Historias cargadas:", len(entidades_por_historia))

# ===============================
# ALGORITMO 4
# ===============================

def algoritmo_4_analisis_relaciones(entidades_por_historia):
    relaciones_por_historia = []

    for entidades in entidades_por_historia:
        relaciones = []

        rol = entidades["ROL"][0] if entidades["ROL"] else None
        accion = entidades["ACCIÓN"][0] if entidades["ACCIÓN"] else None
        objeto = entidades["OBJETO"][0] if entidades["OBJETO"] else None
        beneficio = entidades["BENEFICIO"][0] if entidades["BENEFICIO"] else None

        # ROL → ACCIÓN
        if rol and accion:
            relaciones.append((rol, "realiza", accion))

        # ACCIÓN → OBJETO
        if accion and objeto:
            relaciones.append((accion, "afecta", objeto))

        # ACCIÓN → BENEFICIO
        if accion and beneficio:
            relaciones.append((accion, "produce", beneficio))

        relaciones_por_historia.append(relaciones)

    return relaciones_por_historia

# ===============================
# EJECUCIÓN Y GUARDADO
# ===============================

relaciones_por_historia = algoritmo_4_analisis_relaciones(entidades_por_historia)

with open(archivo_relaciones, 'w', encoding='latin-1') as f:
    json.dump(relaciones_por_historia, f, ensure_ascii=False, indent=2)

print("Archivo de relaciones guardado en:")
print(archivo_relaciones)

import os
import json

# ===============================
# RUTAS
# ===============================

archivo_relaciones = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo4_relaciones_g13-planningpoker.json'

carpeta_destino = '/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis'
archivo_modelo = os.path.join(
    carpeta_destino,
    'algoritmo5_modelo_conocimiento_g13-planningpoker.json'
)

# ===============================
# CARGA DE RELACIONES
# ===============================

with open(archivo_relaciones, 'r', encoding='latin-1') as f:
    relaciones_por_historia = json.load(f)

print("Historias cargadas:", len(relaciones_por_historia))

# ===============================
# ALGORITMO 5
# ===============================

def algoritmo_5_construccion_modelo_conocimiento(relaciones_por_historia):
    modelo = {}

    for idx, relaciones in enumerate(relaciones_por_historia, start=1):
        historia_id = f"historia_{idx}"

        modelo[historia_id] = {
            "ROL": None,
            "ACCIÓN": None,
            "OBJETO": None,
            "BENEFICIO": None
        }

        for sujeto, relacion, objeto in relaciones:
            if relacion == "realiza":
                modelo[historia_id]["ROL"] = sujeto
                modelo[historia_id]["ACCIÓN"] = objeto

            elif relacion == "afecta":
                modelo[historia_id]["OBJETO"] = objeto

            elif relacion == "produce":
                modelo[historia_id]["BENEFICIO"] = objeto

    return modelo

# ===============================
# EJECUCIÓN Y GUARDADO
# ===============================

modelo_conocimiento = algoritmo_5_construccion_modelo_conocimiento(relaciones_por_historia)

with open(archivo_modelo, 'w', encoding='latin-1') as f:
    json.dump(modelo_conocimiento, f, ensure_ascii=False, indent=2)

print("Modelo de conocimiento guardado en:")
print(archivo_modelo)

import json

# =========================
# MÉTRICAS INDIVIDUALES
# =========================

def metric_completitud(entidades):
    requeridos = ["ROL", "ACCIÓN", "OBJETO", "BENEFICIO"]
    presentes = sum(1 for r in requeridos if entidades.get(r))
    return presentes / len(requeridos)


def metric_atomicidad(entidades):
    acciones = entidades.get("ACCIÓN", [])
    return 1.0 if len(acciones) == 1 else 0.0


def metric_concision(tokens, max_tokens=30):
    if not tokens:
        return 0.0
    if len(tokens) <= max_tokens:
        return 1.0
    exceso = len(tokens) - max_tokens
    return max(0.5, 1 - exceso / max_tokens)


def metric_claridad(entidades):
    verbos_vagos = {
        "hacer", "manejar", "gestionar",
        "realizar", "permitir", "poder"
    }
    acciones = [a.lower() for a in entidades.get("ACCIÓN", [])]
    if any(v in verbos_vagos for v in acciones):
        return 0.5
    return 1.0


def puntuacion_global(metricas):
    return round(sum(metricas.values()) / len(metricas), 2)

# =========================
# ALGORITMO 6
# =========================

def algoritmo_6_metricas_calidad(entidades_por_historia, tokens_por_historia):
    resultados = []

    for entidades, tokens in zip(entidades_por_historia, tokens_por_historia):
        metricas = {
            "completitud": metric_completitud(entidades),
            "atomicidad": metric_atomicidad(entidades),
            "claridad": metric_claridad(entidades),
            "concisión": metric_concision(tokens)
        }

        metricas["calidad_global"] = puntuacion_global(metricas)
        resultados.append(metricas)

    return resultados

# =========================
# EJECUCIÓN
# =========================

with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo3_entidades_g13-planningpoker.json", "r", encoding="latin-1") as f:
    entidades = json.load(f)

with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo1_tokenizacion_g13-planningpoker.json", "r", encoding="latin-1") as f:
    tokens = json.load(f)

metricas = algoritmo_6_metricas_calidad(entidades, tokens)

with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo6_metricas_calidad_g13-planningpoker.json", "w", encoding="latin-1") as f:
    json.dump(metricas, f, ensure_ascii=False, indent=2)

import json
import os

# =========================
# CONFIGURACIÓN
# =========================

VERBOS_GENERICOS = {
    "quiero", "quisiera", "poder", "pueda",
    "permitir", "permitirme", "desear"
}

CONECTORES_BENEFICIO = [
    "para", "pueda", "con el fin", "de modo que"
]

def beneficio_valido(texto):
    texto = texto.lower()
    return any(c in texto for c in CONECTORES_BENEFICIO)

# =========================
# ALGORITMO 7
# =========================

def algoritmo_7_generar_gold(
    historias_originales,
    entidades_detectadas,
    nombre_dataset,
    ruta_salida,
    limite=50
):
    gold = []

    for i, (texto, entidades) in enumerate(
        zip(historias_originales[:limite], entidades_detectadas[:limite]),
        start=1
    ):
        anotaciones = {}

        if entidades.get("ROL"):
            anotaciones["ROL"] = entidades["ROL"]

        acciones_filtradas = [
            a for a in entidades.get("ACCIÓN", [])
            if a.lower() not in VERBOS_GENERICOS
        ]
        if acciones_filtradas:
            anotaciones["ACCIÓN"] = acciones_filtradas

        if entidades.get("OBJETO"):
            anotaciones["OBJETO"] = entidades["OBJETO"]

        beneficios_validos = [
            b for b in entidades.get("BENEFICIO", [])
            if beneficio_valido(b)
        ]
        if beneficios_validos:
            anotaciones["BENEFICIO"] = beneficios_validos

        gold.append({
            "id": i,
            "texto": texto,
            "anotaciones": anotaciones
        })

    nombre_archivo = f"gold_{nombre_dataset}_30.json"
    ruta_completa = os.path.join(ruta_salida, nombre_archivo)

    with open(ruta_completa, "w", encoding="utf-8") as f:
        json.dump(gold, f, ensure_ascii=False, indent=2)

    return ruta_completa


# historias originales (texto)
with open(
    "/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/traducciones/g13-planningpoker-traducido.txt",
    "r",
    encoding="latin-1"
) as f:
    historias = [line.strip() for line in f if line.strip()]


# entidades del algoritmo 3
with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo3_entidades_g13-planningpoker.json", "r", encoding="latin-1") as f:
    entidades = json.load(f)

ruta = algoritmo_7_generar_gold(
    historias_originales=historias,
    entidades_detectadas=entidades,
    nombre_dataset="planningpoker",
    ruta_salida="/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis"
)

print("✔ Gold standard generado en:", ruta)

def overlap_parcial(a, b):
    """
    Calcula solapamiento léxico entre dos expresiones
    """
    set_a = set(a.split())
    set_b = set(b.split())

    if not set_a or not set_b:
        return 0

    return len(set_a & set_b) / max(len(set_a), len(set_b))

import time

# ===============================
# CONFIGURACIÓN SEMÁNTICA
# ===============================

VERBOS_GENERICOS = {
    "hacer", "tener", "poder", "ser", "estar", "mantener",
    "querer", "quisiera", "permitir", "permitirme"
}

def beneficio_valido(texto):
    """
    Valida que el beneficio tenga intención explícita
    """
    texto = texto.lower()
    return any(p in texto for p in [
        "para", "pueda", "con el fin", "de modo que"
    ])

# ===============================
# MÉTRICAS DE TIEMPO
# ===============================

def evaluar_tiempo_pipeline(
    tokens_fn,
    pos_fn,
    entidades_fn,
    relaciones_fn,
    metricas_fn,
    entrada
):
    inicio = time.time()

    tokens = tokens_fn(entrada)
    pos = pos_fn(tokens)
    entidades = entidades_fn(pos)
    relaciones = relaciones_fn(entidades)
    metricas = metricas_fn(entidades, tokens)

    fin = time.time()

    tiempo_total = fin - inicio
    tiempo_promedio = tiempo_total / len(tokens)

    return {
        "tiempo_total_segundos": round(tiempo_total, 4),
        "tiempo_promedio_por_historia": round(tiempo_promedio, 4)
    }

# ===============================
# MÉTRICAS CLÁSICAS
# ===============================

def precision(correctas, detectadas):
    return correctas / detectadas if detectadas > 0 else 0

def recall(correctas, reales):
    return correctas / reales if reales > 0 else 0

# ===============================
# EVALUACIÓN PRECISIÓN / RECALL
# ===============================

def evaluar_precision_recall_por_tipo(entidades_detectadas, gold_standard, umbral=0.5):
    resultados = {}

    for tipo in ["ROL", "ACCIÓN", "OBJETO", "BENEFICIO"]:
        correctas = 0
        detectadas = 0
        reales = 0

        for auto, gold in zip(entidades_detectadas, gold_standard):
            auto_vals = auto.get(tipo, [])
            gold_vals = gold.get("anotaciones", {}).get(tipo, [])

            detectadas += len(auto_vals)
            reales += len(gold_vals)

            for a in auto_vals:
                a = a.lower().strip()

                # filtros semánticos
                if tipo == "ACCIÓN" and a in VERBOS_GENERICOS:
                    continue
                if tipo == "BENEFICIO" and not beneficio_valido(a):
                    continue

                for g in gold_vals:
                    g = g.lower().strip()

                    if overlap_parcial(a, g) >= umbral:
                        correctas += 1
                        break

        resultados[tipo] = {
            "precision": round(precision(correctas, detectadas), 2),
            "recall": round(recall(correctas, reales), 2)
        }

    return resultados

# ===============================
# PROMEDIO DE MÉTRICAS GLOBALES
# ===============================

def evaluar_metricas_globales(metricas_por_historia):
    promedio = {}
    claves = metricas_por_historia[0].keys()

    for k in claves:
        promedio[k] = round(
            sum(m[k] for m in metricas_por_historia) / len(metricas_por_historia), 2
        )

    return promedio

# Cargar archivos
with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo3_entidades_g13-planningpoker.json", "r", encoding="latin-1") as f:
    entidades = json.load(f)

with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/algoritmo1_tokenizacion_g13-planningpoker.json", "r", encoding="latin-1") as f:
    tokens = json.load(f)

with open("/content/drive/MyDrive/PROYECTO DE TESIS/Dataset/requerimientos/Analisis/gold_planningpoker_30.json", "r", encoding="utf-8") as f:
    gold = json.load(f)

# Evaluación
metricas_calidad = algoritmo_6_metricas_calidad(entidades, tokens)
precision_recall_por_tipo = evaluar_precision_recall_por_tipo(entidades, gold)

print("MÉTRICAS DE CALIDAD PROMEDIO")
print(evaluar_metricas_globales(metricas_calidad))

print("PRECISIÓN Y RECALL POR TIPO")
print(precision_recall_por_tipo)